-- =============================================================
-- Car Parts B2B Store - Auth schema (users + role enum)
-- Run alongside schema.postgres.sql. Order doesn't matter:
-- the `set_updated_at` function is created with CREATE OR REPLACE
-- so either file may run first.
-- =============================================================

-- pgcrypto exposes crypt() / gen_salt() — used to hash the admin
-- password at seed time so we never ship a plaintext password.
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- Re-run safe.
DROP TABLE IF EXISTS users CASCADE;
DROP TYPE  IF EXISTS user_role;

-- 3 fixed roles. ENUM keeps it tight; if more roles appear later use
-- ALTER TYPE user_role ADD VALUE '...'.
CREATE TYPE user_role AS ENUM ('admin', 'seller', 'customer');

-- Shared trigger function for updated_at. Idempotent.
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at := NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TABLE users (
  id            INTEGER      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email         VARCHAR(150) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  full_name     VARCHAR(200) NOT NULL,
  role          user_role    NOT NULL DEFAULT 'customer',
  is_active     BOOLEAN      NOT NULL DEFAULT TRUE,
  created_at    TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  updated_at    TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_users_role      ON users(role);
CREATE INDEX idx_users_is_active ON users(is_active);

CREATE TRIGGER users_set_updated_at
BEFORE UPDATE ON users
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- =============================================================
-- Seed: admin user
-- Plaintext password (only for local/dev): Admin123!
-- Stored as a bcrypt hash via pgcrypto's crypt() + gen_salt('bf', 10).
-- bcryptjs in the backend verifies $2a$10$... hashes produced here.
-- =============================================================

INSERT INTO users (email, password_hash, full_name, role)
VALUES (
  'admin@test.com',
  crypt('Admin123!', gen_salt('bf', 10)),
  'Admin User',
  'admin'
);

-- Keep the identity sequence aligned with the last seeded id.
SELECT setval(pg_get_serial_sequence('users', 'id'), (SELECT MAX(id) FROM users));
