-- =============================================================
-- Car Parts B2B Store - PostgreSQL Schema (Supabase compatible)
-- Tables match the columns read/written by the Express backend:
-- manufacturers, categories, products, product_images,
-- vehicle_brands, vehicle_models, engines, vehicles,
-- product_compatibility, orders, order_items.
-- =============================================================

-- Clean slate (re-run safe). CASCADE removes dependent FKs.
DROP TABLE IF EXISTS order_items           CASCADE;
DROP TABLE IF EXISTS orders                CASCADE;
DROP TABLE IF EXISTS product_compatibility CASCADE;
DROP TABLE IF EXISTS product_images        CASCADE;
DROP TABLE IF EXISTS products              CASCADE;
DROP TABLE IF EXISTS manufacturers         CASCADE;
DROP TABLE IF EXISTS vehicles              CASCADE;
DROP TABLE IF EXISTS engines               CASCADE;
DROP TABLE IF EXISTS vehicle_models        CASCADE;
DROP TABLE IF EXISTS vehicle_brands        CASCADE;
DROP TABLE IF EXISTS categories            CASCADE;

DROP FUNCTION IF EXISTS set_updated_at();

DROP TYPE IF EXISTS payment_status;
DROP TYPE IF EXISTS fulfillment_status;
DROP TYPE IF EXISTS compat_position;
DROP TYPE IF EXISTS body_type;
DROP TYPE IF EXISTS fuel_type;

-- =============================================================
-- ENUM types
-- =============================================================

CREATE TYPE fuel_type AS ENUM ('gasoline', 'diesel', 'flex', 'cng', 'hybrid', 'ev');

CREATE TYPE body_type AS ENUM (
  'sedan', 'hatchback', 'pickup', 'suv', 'coupe',
  'wagon', 'van', 'convertible', 'minivan'
);

CREATE TYPE compat_position AS ENUM (
  'front', 'rear', 'left', 'right',
  'front_left', 'front_right', 'rear_left', 'rear_right',
  'universal'
);

CREATE TYPE payment_status AS ENUM (
  'pending', 'authorized', 'paid', 'refunded', 'failed'
);

CREATE TYPE fulfillment_status AS ENUM (
  'not_shipped', 'preparing', 'shipped', 'delivered', 'returned', 'cancelled'
);

-- =============================================================
-- Trigger function for auto-updating `updated_at`
-- (PostgreSQL has no `ON UPDATE CURRENT_TIMESTAMP` clause.)
-- =============================================================
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at := NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- =============================================================
-- CATALOG
-- =============================================================

-- categories: hierarchical (parent_id self-FK).
-- `name` is the technical EN label; `display_name` is the ES UI label.
CREATE TABLE categories (
  id           INTEGER      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  parent_id    INTEGER      REFERENCES categories(id) ON DELETE SET NULL,
  name         VARCHAR(100) NOT NULL,
  display_name VARCHAR(150) NOT NULL,
  slug         VARCHAR(160) NOT NULL UNIQUE,
  sort_order   INTEGER      NOT NULL DEFAULT 0,
  is_active    BOOLEAN      NOT NULL DEFAULT TRUE,
  created_at   TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  updated_at   TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_categories_parent ON categories(parent_id);
CREATE INDEX idx_categories_active ON categories(is_active);

CREATE TRIGGER categories_set_updated_at
BEFORE UPDATE ON categories
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- manufacturers: part brand (Bosch, Ferodo, NGK, ...).
CREATE TABLE manufacturers (
  id         INTEGER      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name       VARCHAR(100) NOT NULL UNIQUE,
  slug       VARCHAR(120) NOT NULL UNIQUE,
  country    VARCHAR(60),
  website    VARCHAR(255),
  is_active  BOOLEAN      NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

-- =============================================================
-- VEHICLES & COMPATIBILITY
-- =============================================================

CREATE TABLE vehicle_brands (
  id         INTEGER      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name       VARCHAR(100) NOT NULL UNIQUE,
  slug       VARCHAR(120) NOT NULL UNIQUE,
  is_active  BOOLEAN      NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

CREATE TABLE vehicle_models (
  id         INTEGER      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  brand_id   INTEGER      NOT NULL REFERENCES vehicle_brands(id) ON DELETE RESTRICT,
  name       VARCHAR(100) NOT NULL,
  slug       VARCHAR(140) NOT NULL UNIQUE,
  is_active  BOOLEAN      NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  UNIQUE (brand_id, name)
);

CREATE TABLE engines (
  id              INTEGER      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code            VARCHAR(50)  NOT NULL UNIQUE,
  displacement_cc INTEGER      NOT NULL CHECK (displacement_cc > 0),
  fuel_type       fuel_type    NOT NULL,
  horsepower      SMALLINT,
  description     VARCHAR(255),
  created_at      TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_engines_fuel ON engines(fuel_type);

-- vehicles: model + engine + trim + year_from/year_to + body_type.
-- Each row represents a "generation" you can map products to.
CREATE TABLE vehicles (
  id         INTEGER     GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  model_id   INTEGER     NOT NULL REFERENCES vehicle_models(id) ON DELETE RESTRICT,
  engine_id  INTEGER     NOT NULL REFERENCES engines(id)        ON DELETE RESTRICT,
  trim       VARCHAR(80),
  body_type  body_type   NOT NULL,
  year_from  SMALLINT    NOT NULL CHECK (year_from BETWEEN 1950 AND 2100),
  year_to    SMALLINT    CHECK (year_to IS NULL OR year_to BETWEEN 1950 AND 2100),
  notes      VARCHAR(255),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CHECK (year_to IS NULL OR year_to >= year_from),
  UNIQUE (model_id, engine_id, trim, year_from)
);

CREATE INDEX idx_vehicles_engine     ON vehicles(engine_id);
CREATE INDEX idx_vehicles_year_range ON vehicles(year_from, year_to);
CREATE INDEX idx_vehicles_body_type  ON vehicles(body_type);

-- =============================================================
-- PRODUCTS
-- =============================================================

CREATE TABLE products (
  id                INTEGER       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category_id       INTEGER       NOT NULL REFERENCES categories(id)    ON DELETE RESTRICT,
  manufacturer_id   INTEGER       NOT NULL REFERENCES manufacturers(id) ON DELETE RESTRICT,
  sku               VARCHAR(60)   NOT NULL UNIQUE,
  part_number       VARCHAR(80),
  slug              VARCHAR(200)  NOT NULL UNIQUE,
  name              VARCHAR(200)  NOT NULL,
  short_description VARCHAR(500),
  description       TEXT,
  price             NUMERIC(12,2) NOT NULL CHECK (price >= 0),
  cost              NUMERIC(12,2) CHECK (cost IS NULL OR cost >= 0),
  currency          CHAR(3)       NOT NULL DEFAULT 'ARS',
  stock             INTEGER       NOT NULL DEFAULT 0 CHECK (stock >= 0),
  stock_reserved    INTEGER       NOT NULL DEFAULT 0,
  is_active         BOOLEAN       NOT NULL DEFAULT TRUE,
  created_at        TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
  updated_at        TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
  CHECK (stock_reserved >= 0 AND stock_reserved <= stock),
  UNIQUE (manufacturer_id, part_number)
);

CREATE INDEX idx_products_category_active ON products(category_id, is_active);
CREATE INDEX idx_products_part_number     ON products(part_number);

CREATE TRIGGER products_set_updated_at
BEFORE UPDATE ON products
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE product_images (
  id         INTEGER      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id INTEGER      NOT NULL REFERENCES products(id) ON DELETE CASCADE,
  url        VARCHAR(500) NOT NULL,
  alt_text   VARCHAR(200),
  position   INTEGER      NOT NULL DEFAULT 0,
  is_primary BOOLEAN      NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_product_images_primary ON product_images(product_id, is_primary);

-- N:M between products and vehicles.
CREATE TABLE product_compatibility (
  product_id INTEGER         NOT NULL REFERENCES products(id) ON DELETE CASCADE,
  vehicle_id INTEGER         NOT NULL REFERENCES vehicles(id) ON DELETE CASCADE,
  position   compat_position NOT NULL DEFAULT 'universal',
  notes      VARCHAR(255),
  created_at TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
  PRIMARY KEY (product_id, vehicle_id)
);

CREATE INDEX idx_compat_vehicle  ON product_compatibility(vehicle_id);
CREATE INDEX idx_compat_position ON product_compatibility(position);

-- =============================================================
-- SALES
-- =============================================================

-- orders: payment_status and fulfillment_status are independent.
-- customer_id is a plain integer (no customers table in this MVP);
-- the customer's name/email/phone are snapshotted on the row.
CREATE TABLE orders (
  id                   INTEGER            GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_code           VARCHAR(30)        NOT NULL UNIQUE,
  customer_id          INTEGER,

  customer_name        VARCHAR(200)       NOT NULL,
  customer_email       VARCHAR(150)       NOT NULL,
  customer_phone       VARCHAR(40),

  subtotal             NUMERIC(12,2)      NOT NULL DEFAULT 0 CHECK (subtotal        >= 0),
  tax_amount           NUMERIC(12,2)      NOT NULL DEFAULT 0 CHECK (tax_amount      >= 0),
  shipping_cost        NUMERIC(12,2)      NOT NULL DEFAULT 0 CHECK (shipping_cost   >= 0),
  discount_amount      NUMERIC(12,2)      NOT NULL DEFAULT 0 CHECK (discount_amount >= 0),
  total                NUMERIC(12,2)      NOT NULL DEFAULT 0 CHECK (total           >= 0),
  currency             CHAR(3)            NOT NULL DEFAULT 'ARS',

  payment_status       payment_status     NOT NULL DEFAULT 'pending',
  fulfillment_status   fulfillment_status NOT NULL DEFAULT 'not_shipped',

  payment_method       VARCHAR(50),
  payment_reference    VARCHAR(100),
  shipping_method      VARCHAR(50),
  tracking_number      VARCHAR(100),

  shipping_street      VARCHAR(200),
  shipping_number      VARCHAR(20),
  shipping_floor       VARCHAR(40),
  shipping_city        VARCHAR(100),
  shipping_province    VARCHAR(100),
  shipping_postal_code VARCHAR(20),
  shipping_country     CHAR(2)            NOT NULL DEFAULT 'AR',
  shipping_notes       VARCHAR(500),

  notes                VARCHAR(500),

  created_at           TIMESTAMPTZ        NOT NULL DEFAULT NOW(),
  updated_at           TIMESTAMPTZ        NOT NULL DEFAULT NOW(),
  paid_at              TIMESTAMPTZ,
  shipped_at           TIMESTAMPTZ,
  delivered_at         TIMESTAMPTZ,
  cancelled_at         TIMESTAMPTZ
);

CREATE INDEX idx_orders_customer           ON orders(customer_id);
CREATE INDEX idx_orders_customer_email     ON orders(customer_email);
CREATE INDEX idx_orders_payment_status     ON orders(payment_status);
CREATE INDEX idx_orders_fulfillment_status ON orders(fulfillment_status);
CREATE INDEX idx_orders_created_at         ON orders(created_at);

CREATE TRIGGER orders_set_updated_at
BEFORE UPDATE ON orders
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE order_items (
  id                    INTEGER       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id              INTEGER       NOT NULL REFERENCES orders(id)   ON DELETE CASCADE,
  product_id            INTEGER       NOT NULL REFERENCES products(id) ON DELETE RESTRICT,
  product_name_snapshot VARCHAR(200)  NOT NULL,
  product_sku_snapshot  VARCHAR(60)   NOT NULL,
  quantity              INTEGER       NOT NULL CHECK (quantity > 0),
  unit_price            NUMERIC(12,2) NOT NULL CHECK (unit_price >= 0),
  discount_amount       NUMERIC(12,2) NOT NULL DEFAULT 0 CHECK (discount_amount >= 0),
  line_total            NUMERIC(12,2) NOT NULL CHECK (line_total >= 0)
);

CREATE INDEX idx_order_items_order   ON order_items(order_id);
CREATE INDEX idx_order_items_product ON order_items(product_id);
